"""
network/relay_manager.py
------------------------

Relay Manager.

Executes a relay path generated by GarlicRouter.

Responsibilities
----------------
• Maintain registered relay nodes.
• Execute a relay path.
• Collect routing statistics.

The Relay Manager NEVER chooses the route.
That responsibility belongs to GarlicRouter.
"""

from __future__ import annotations

import time

from .garlic_message import GarlicMessage
from .relay import Relay


class RelayManager:
    """
    Executes Garlic Messages through a relay path.
    """

    def __init__(self) -> None:

        self._relays: dict[str, Relay] = {}

        self.messages_routed = 0

        self.total_route_time_ms = 0.0

        self.relay_logs: list[dict] = []
    # ----------------------------------------------------------
    # Relay Management
    # ----------------------------------------------------------

    def add_relay(
        self,
        relay: Relay,
    ) -> None:
        """
        Register a relay.
        """

        self._relays[relay.relay_id] = relay

    def remove_relay(
        self,
        relay_id: str,
    ) -> None:
        """
        Remove a relay.
        """

        self._relays.pop(
            relay_id,
            None,
        )

    def get_relay(
        self,
        relay_id: str,
    ) -> Relay:
        """
        Retrieve a relay.
        """

        if relay_id not in self._relays:
            raise KeyError(
                f"Relay '{relay_id}' not found."
            )

        return self._relays[relay_id]

    @property
    def relays(self) -> list[Relay]:
        """
        Return all registered relays.
        """

        return list(
            self._relays.values()
        )

    # ----------------------------------------------------------
    # Route Execution
    # ----------------------------------------------------------

    def execute_route(
        self,
        garlic: GarlicMessage,
        route: list[Relay],
    ) -> GarlicMessage:
        """
        Execute a Garlic Message through
        the supplied relay path.
        """

        self.relay_logs.clear()

        start = time.perf_counter()

        for relay in route:

            relay_start = time.perf_counter()

            garlic = relay.forward(garlic)

            relay_elapsed = (
                time.perf_counter() - relay_start
            )

            self.relay_logs.append(
                {
                    "relay": relay.relay_id,
                    "processing_time": round(
                        relay_elapsed,
                        4,
                    ),
                }
            )

        elapsed = (
            time.perf_counter() - start
        ) * 1000

        self.messages_routed += 1

        self.total_route_time_ms += elapsed

        return garlic

    # ----------------------------------------------------------
    # Statistics
    # ----------------------------------------------------------

    @property
    def average_route_time_ms(self) -> float:
        """
        Average routing latency.
        """

        if self.messages_routed == 0:
            return 0.0

        return (
            self.total_route_time_ms
            / self.messages_routed
        )

    def stats(self) -> dict:
        """
        Return routing statistics.
        """

        return {

            "registered_relays": len(
                self._relays
            ),

            "online_relays": sum(
                relay.online
                for relay in self._relays.values()
            ),

            "messages_routed": self.messages_routed,

            "average_route_time_ms": round(
                self.average_route_time_ms,
                3,
            ),
        }

    # ----------------------------------------------------------
    # Helpers
    # ----------------------------------------------------------

    def __len__(self) -> int:

        return len(
            self._relays
        )

    def __iter__(self):

        return iter(
            self._relays.values()
        )

    def __repr__(self) -> str:

        return (
            f"RelayManager("
            f"relays={len(self)}, "
            f"messages={self.messages_routed}"
            f")"
        )
    