"""
agents/doctor.py
────────────────
Doctor Agent (Ad)

The Doctor Agent is responsible for converting a patient's diagnosis
into a structured surgical plan using a Large Language Model.

Workflow
--------
Diagnosis JSON
        │
        ▼
Doctor Prompt
        │
        ▼
LLM (Llama 3.2 / VibeThinker 1.5)
        │
        ▼
Structured Surgery Plan (JSON)

Paper Reference
---------------
• Section III-C — Doctor Agent
• Section III-E — Doctor Interaction Layer
• Equation (14)
• Algorithm 2 — Step 1
"""

import json

from typing import Any

from langchain_core.language_models import BaseLanguageModel

from config import settings

from utils.base_agent import BaseAgent
from utils.logger import setup_logger


class DoctorAgent(BaseAgent):
    """
    Doctor Agent

    Responsibilities
    ----------------
    • Read patient diagnosis
    • Invoke the configured language model
    • Generate a structured surgery plan
    • Return JSON for downstream agents
    """

    def __init__(self, llm: BaseLanguageModel) -> None:
        super().__init__(
            model=llm,
            prompt_path=settings.PROMPTS_DIR / "doctor.txt"
        )

        self.log = setup_logger("agents.doctor")

        self.log.info("=" * 60)
        self.log.info("Doctor Agent Initialised")
        self.log.info(f"Prompt : {settings.PROMPTS_DIR / 'doctor.txt'}")
        self.log.info("=" * 60)

    def run(self, diagnosis: dict[str, Any]) -> dict:
        """
        Generate a structured surgical plan.

        Parameters
        ----------
        diagnosis : dict
            Patient diagnosis.

        Returns
        -------
        dict
            Structured surgery plan generated by the LLM.
        """

        if not diagnosis:
            raise ValueError("Diagnosis data is empty.")

        patient_id = diagnosis.get("patient_id", "Unknown")

        self.log.info(
            f"Generating surgery plan | Patient: {patient_id}"
        )

        try:

            diagnosis_json = json.dumps(
                diagnosis,
                ensure_ascii=False,
                separators=(",", ":")
            )

            self.log.info(f"Prompt variables: {self.prompt.input_variables}")

            result = self.invoke(
                {
                    "diagnosis": diagnosis_json
                }
            )

            self.log.info(
                "Surgery plan generated successfully."
            )

            if isinstance(result, dict):

                self.log.info(
                    f"Generated {len(result.get('surgical_steps', []))} surgical steps."
                )

            return result

        except Exception as exc:

            self.log.exception(
                f"Doctor Agent failed for patient {patient_id}"
            )
            
            raise RuntimeError(
                "Doctor Agent failed to generate a surgery plan."
            ) from exc
